### ISSUE TITLE
Theme download links are broken

### ISSUE THREAD

**Issue by thSoft** [semantic-ui-forest/semantic-ui-forest#27]
E.g.
`https://github.com/semantic-ui-forest/forest-themes/blob/master/dist/semantic-ui/semantic.chubby.min.css`
should be
`https://github.com/semantic-ui-forest/forest-themes/blob/master/dist/semantic-ui/v2/semantic.chubby.min.css`

**Comment by xiaohanyu** [comment]
Hi, 

Thanks for report. The website is under a heavy refactoring..

**Comment by xiaohanyu** [comment]
https://semantic-ui-forest.com/

website refactoring almost done.

Themee links will be pushed to npm.

Give me some more time.
